#!/system/bin/sh
mount -o remount,rw /system
cp /data/local/tmp/su /system/xbin
chmod 4755 /system/xbin/su
/data/local/tmp/sh "$@"
#/data/local/tmp/montoya_diag.sh "$@"
#/system/xbin/montoya_diag.sh "$@"
